[package]
name = "rust-ig-profpic"
version = "0.1.0"
authors = ["Muhammad Syifa <emsifa@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "1.0"
actix-files = "0.1.7"
env_logger = "0.7.1"
serde = "1.0.102"
reqwest = "0.9.22"
regex = "1.3.1"
